[build]
publish = "public"
command = "sh do hugo"

[build.environment]
<<<<<<< HEAD
HUGO_VERSION = "0.129.0"
=======
HUGO_VERSION = "0.135.0"
NODE_VERSION = "23.5.0"
>>>>>>> 3c1c646474044268b088da6ce391479f7976107c

[context.production]
publish = "public"
command = "sh do hugo"

[[plugins]]
  package = "netlify-plugin-hugo-cache-resources"