export const STRIPE_SESSION_MIN_TTL_SECONDS = 30 * 60
export const STRIPE_SESSION_MAX_TTL_SECONDS = 24 * 60 * 60
export const STRIPE_IDEMPOTENCY_RETRY_TTL_SECONDS = 23 * 60 * 60
export const CHECKOUT_EXPIRY_MARGIN_SECONDS = 5 * 60
export const CHECKOUT_RECOVERY_TTL_SECONDS = STRIPE_IDEMPOTENCY_RETRY_TTL_SECONDS + STRIPE_SESSION_MAX_TTL_SECONDS + CHECKOUT_EXPIRY_MARGIN_SECONDS
