#!/usr/bin/env node

/*
Purpose: Synchronize generated root README.md and AGENTS.md from the theme,
and scaffold dna/_index.md when a new project does not have one.
Run from: Consumer project root through `sh do root-docs [--force]`.
Writes: Root README.md and AGENTS.md; creates dna/_index.md only when absent.
*/

import fs from 'node:fs'
import path from 'node:path'
import process from 'node:process'
import { fileURLToPath } from 'node:url'

const scriptDir = path.dirname(fileURLToPath(import.meta.url))
const themeDir = path.resolve(scriptDir, '..')
const projectDir = process.cwd()
const force = process.argv.slice(2).includes('--force')
const generatedPrefix = '<!-- Generated by `sh do root-docs`'
const projectName = readProjectPackage().name || path.basename(projectDir)

const targets = [
  { file: 'README.md', replacements: { '{{PROJECT_NAME}}': projectName } },
  { file: 'AGENTS.md', replacements: {} }
]

const unmanaged = []

for (const target of targets) {
  const file = path.join(projectDir, target.file)
  if (!fs.existsSync(file)) continue
  const source = fs.readFileSync(file, 'utf8')
  if (!source.startsWith(generatedPrefix)) unmanaged.push(target.file)
}

if (unmanaged.length > 0 && !force) {
  fail(`${unmanaged.join(' and ')} must be migrated. Move project-specific information to dna/, then run \`sh do root-docs --force\`.`)
}

const dnaFile = path.join(projectDir, 'dna', '_index.md')
if (unmanaged.length > 0 && !fs.existsSync(dnaFile)) {
  fail('Create dna/_index.md and preserve relevant information from the legacy root documents before using --force.')
}

if (!fs.existsSync(dnaFile)) {
  fs.mkdirSync(path.dirname(dnaFile), { recursive: true })
  fs.copyFileSync(path.join(themeDir, 'templates', 'dna', '_index.md'), dnaFile)
  console.log('Created dna/_index.md; complete it with this project\'s particulars.')
}

for (const target of targets) syncFile(target)

function syncFile ({ file, replacements }) {
  const target = path.join(projectDir, file)
  let next = fs.readFileSync(path.join(themeDir, 'templates', 'root', file), 'utf8')
  for (const [search, replacement] of Object.entries(replacements)) {
    next = next.replaceAll(search, replacement)
  }

  const source = fs.existsSync(target) ? fs.readFileSync(target, 'utf8') : null
  if (source === next) {
    console.log(`${file} is current.`)
    return
  }

  fs.writeFileSync(target, next, 'utf8')
  console.log(`${source === null ? 'Created' : 'Updated'} ${file}.`)
}

function readProjectPackage () {
  const file = path.join(projectDir, 'package.json')
  if (!fs.existsSync(file)) return {}
  return JSON.parse(fs.readFileSync(file, 'utf8'))
}

function fail (message) {
  console.error(message)
  process.exit(2)
}
